# make this a resuable workflow for running pnpm install and build
on:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: boolean
        default: false
        description: Whether to deploy the built project to GitHub Pages
      dist_path:
        required: false
        type: string
        default: dist/
        description: The path to the built project. Defaults to dist/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        if: inputs.deploy
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      # Set up Node.js (using the latest LTS version)
      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '22.14' # Use the latest LTS version of Node.js
          cache: 'pnpm'

      # Install dependencies using pnpm
      - name: Install dependencies
        run: corepack enable && pnpm install

      # Build the Vite project
      - name: Build project (production)
        run: pnpm build

      - name: Upload build to pages
        if: inputs.deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.dist_path }}
