name: Deploy to GitHub Pages

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    name: Build project
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'github-pages' || github.ref_name }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - uses: ./.github/workflows/build.yml
        with:
          deploy: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
